version: 2.1

# add your orb below, to be used in integration tests (note: a @dev:alpha
# release must exist; you'll need to publish manually at least once)
# you can use scripts/publish-alpha.sh to publish a @dev:alpha release
orbs:
  cli: circleci/circleci-cli@volatile
  prebuild-orb: netgaintechnology/prebuild-orb@volatile
  orb-tools: circleci/orb-tools@volatile

workflows:
  # this `lint-pack_validate_publish-dev` workflow will run on any commit
  lint-pack_validate_publish-dev:
    jobs:
      # lint your destructured orb YAML and markdown files
      - prebuild-orb/yaml_lint
      - prebuild-orb/markdown_lint

      # pack your orb YAML files to a single orb.yml
      # validate the orb.yml file to ensure it is well-formed
      - orb-tools/pack:
          requires:
            - prebuild-orb/yaml_lint

      # release dev version of orb, for testing & possible publishing
      # requires a CircleCI API token to be stored as CIRCLE_TOKEN (default)
      # https://circleci.com/docs/2.0/managing-api-tokens
      # store CIRCLE_TOKEN as a project env var or Contexts resource
      # if using Contexts, add your context below
      - orb-tools/publish-dev:
          orb-name: netgaintechnology/prebuild-orb
          requires:
            - orb-tools/pack

  # this `integration-tests_prod-release` workflow will ignore commits
  # it is only triggered by git tags, which are created in the job above
  promote-orb:
    jobs:
      - orb-tools/increment:
          orb-ref: netgaintechnology/prebuild-orb
          filters:
            branches:
              only: master
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: netgaintechnology/prebuild-orb
          add-pr-comment: false
          publish-version-tag: true
          fail-if-semver-not-indicated: false
          ssh-fingerprints: 66:04:99:1b:8e:51:e9:16:64:5f:f3:77:99:67:d6:66
          requires:
            - orb-tools/increment
          filters:
            branches:
              only: master
