version: 2.1

orbs:
  prebuild-orb: netgaintechnology/prebuild-orb@volatile
  orb-tools: circleci/orb-tools@volatile

workflows:
  # this `lint-pack_validate_publish-dev` workflow will run on any commit
  lint-pack_validate_publish-dev:
    jobs:
      # lint your destructured orb YAML and markdown files
      - prebuild-orb/yaml_lint
          filters:
            branches:
              ignore: master
      - prebuild-orb/markdown_lint
          filters:
            branches:
              ignore: master
      # pack your orb YAML files to a single orb.yml
      # validate the orb.yml file to ensure it is well-formed
      - orb-tools/pack:
          requires:
            - prebuild-orb/yaml_lint
          filters:
            branches:
              ignore: master
      # release dev version of orb, for testing & possible publishing
      # requires a CircleCI API token to be stored as CIRCLE_TOKEN (default)
      # https://circleci.com/docs/2.0/managing-api-tokens
      # store CIRCLE_TOKEN as a project env var or Contexts resource
      # if using Contexts, add your context below
      - orb-tools/publish-dev:
          orb-name: netgaintechnology/prebuild-orb
          requires:
            - orb-tools/pack

  # Pack orb and publish new version with patch number incremented
  promote-orb:
    jobs:
      - orb-tools/pack:
          filters:
            branches:
              only: master
      - orb-tools/increment:
          orb-ref: netgaintechnology/prebuild-orb
          attach-workspace: true
          requires:
            - orb-tools/pack
          filters:
            branches:
              only: master

#      # publish a semver version of the orb. relies on
#      # the commit subject containing the text "[semver:patch|minor|major|skip]"
#      # as that will determine whether a patch, minor or major
#      # version will be published or if publishing should
#      # be skipped.
#      # e.g. [semver:patch] will cause a patch version to be published.
#      - orb-tools/dev-promote-prod-from-commit-subject:
#          orb-name: netgaintechnology/prebuild-orb
#          add-pr-comment: false
#          publish-version-tag: true
#          fail-if-semver-not-indicated: true
#          ssh-fingerprints: 66:04:99:1b:8e:51:e9:16:64:5f:f3:77:99:67:d6:66
#          requires:
#            - orb-tools/increment
#          filters:
#            branches:
#              only: master
