version: 2.1

# add your orb below, to be used in integration tests (note: a @dev:alpha
# release must exist; you'll need to publish manually at least once)
# you can use scripts/publish-alpha.sh to publish a @dev:alpha release
orbs:
  cli: circleci/circleci-cli@volatile
  prebuild-orb: netgaintechnology/prebuild-orb@volatile
  orb-tools: circleci/orb-tools@volatile
  prebuild-orb-alpha: netgaintechnology/prebuild-orb@dev:alpha
  queue: eddiewebb/queue@volatile

jobs:
  test-commands:
    parameters:
      executor:
        type: executor

      segment:
        description: >
          The semver segment to increment 'major' or 'minor' or 'patch'
        type: enum
        enum: [major, minor, patch]
        default: patch

    executor: <<parameters.executor>>

    steps:
      - checkout

      - cli/install

      - orb-tools/install-bats
      - orb-tools/pack
      - orb-tools/validate

      - orb-tools/check-env-var-param:
          command-name: Test `check-env-var-param` command with built-in env vars
          param: CIRCLE_BUILD_NUM,CIRCLE_BRANCH,CIRCLE_BUILD_URL,CIRCLE_JOB

      - orb-tools/publish:
          orb-ref: netgaintechnology/prebuild-orb@dev:$CIRCLE_TAG

      - orb-tools/increment:
          orb-ref: netgaintechnology/prebuild-orb
          segment: <<parameters.segment>>

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/
integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [
    test-increment-job-master
  ]

requires_commands_dev: &requires_commands_dev
  [
    test-commands-dev-alpine,
  ]

requires_commands_master: &requires_commands_master
  [
    test-commands-master-alpine,
  ]

workflows:
  # this `lint-pack_validate_publish-dev` workflow will run on any commit
  lint-pack_validate_publish-dev:
    jobs:
      # lint your destructured orb YAML and markdown files
      - prebuild-orb/yaml_lint
      - prebuild-orb/markdown_lint

      # pack your orb YAML files to a single orb.yml
      # validate the orb.yml file to ensure it is well-formed
      - orb-tools/pack:
          source-dir: src
          destination-orb-path: orb.yml
          workspace-path: orb.yml
          artifact-path: orb.yml
          requires:
            - prebuild-orb/yaml_lint

      # release dev version of orb, for testing & possible publishing
      # requires a CircleCI API token to be stored as CIRCLE_TOKEN (default)
      # https://circleci.com/docs/2.0/managing-api-tokens
      # store CIRCLE_TOKEN as a project env var or Contexts resource
      # if using Contexts, add your context below
      - orb-tools/publish-dev:
          orb-name: netgaintechnology/prebuild-orb
          requires:
            - orb-tools/pack

      - queue/block_workflow:
          requires:
            - orb-tools/publish-dev

      # trigger an integration workflow to test the dev version of your orb
      # an SSH key must be stored in your orb's repository and in CircleCI
      # (add the public key as a read/write key on GitHub; add the private
      # key in CircleCI via SSH Permissions, with github.com as Hostname)
      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          ssh-fingerprints: 66:04:99:1b:8e:51:e9:16:64:5f:f3:77:99:67:d6:66
          requires:
            - queue/block_workflow
          filters:
            branches:
              ignore: master

      # by default, the 1st job (above) will trigger only integration tests;
      # the 2nd job (below) may also publish a production orb version
      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          cleanup-tags: true
          ssh-fingerprints: 66:04:99:1b:8e:51:e9:16:64:5f:f3:77:99:67:d6:66
          tag: master
          requires:
            - queue/block_workflow
          filters:
            branches:
              only: master

  # this `integration-tests_prod-release` workflow will ignore commits
  # it is only triggered by git tags, which are created in the job above
  integration-tests_prod-release:
    jobs:
      # triggered by non-master branch commits
      # test commands with executors
      - test-commands:
          name: test-commands-dev-alpine
          executor: orb-tools/alpine
          filters: *integration-dev_filters

      # test jobs
      - orb-tools/pack:
          name: test-pack-job-dev
          workspace-path: orb.yml
          artifact-path: orb.yml
          filters: *integration-dev_filters
          requires: *requires_commands_dev

      - orb-tools/test-in-builds:
          name: test-in-builds-job-dev
          attach-workspace: true
          orb-name: orb-tools
          filters: *integration-dev_filters
          requires: [test-pack-job-dev]
          test-steps:
            - checkout
            - orb-tools/install-bats
            - orb-tools/pack
            - orb-tools/validate
            - orb-tools/publish:
                orb-ref: netgaintechnology/prebuild-orb@dev:$CIRCLE_TAG

      - orb-tools/publish:
          name: test-publish-job-dev
          attach-workspace: true
          orb-ref: netgaintechnology/prebuild-orb@dev:$CIRCLE_TAG
          filters: *integration-dev_filters
          requires:
            - test-pack-job-dev

      - orb-tools/increment:
          name: test-increment-job-dev
          attach-workspace: true
          orb-ref: netgaintechnology/prebuild-orb
          filters: *integration-dev_filters
          requires:
            - test-in-builds-job-dev
            - test-publish-job-dev

      # triggered by master branch commits
      # test commands with executors
      - test-commands:
          name: test-commands-master-alpine
          executor: orb-tools/alpine
          filters: *integration-master_filters

      # test jobs
      - orb-tools/pack:
          name: test-pack-job-master
          workspace-path: orb.yml
          artifact-path: orb.yml
          filters: *integration-master_filters
          requires: *requires_commands_master

      - orb-tools/test-in-builds:
          name: test-in-builds-job-master
          attach-workspace: true
          orb-name: orb-tools
          filters: *integration-master_filters
          requires:
            - test-pack-job-master
          test-steps:
            - checkout
            - orb-tools/install-bats
            - orb-tools/pack
            - orb-tools/validate
            - orb-tools/publish:
                orb-ref: netgaintechnology/prebuild-orb@dev:$CIRCLE_TAG

      - orb-tools/publish:
          name: test-publish-job-master
          attach-workspace: true
          orb-ref: netgaintechnology/prebuild-orb@dev:$CIRCLE_TAG
          filters: *integration-master_filters
          requires:
            - test-pack-job-master

      - orb-tools/increment:
          name: test-increment-job-master
          attach-workspace: true
          orb-ref: netgaintechnology/prebuild-orb
          filters: *integration-master_filters
          requires:
            - test-in-builds-job-master
            - test-publish-job-master

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          orb-name: circleci/orb-tools
          ssh-fingerprints: 66:04:99:1b:8e:51:e9:16:64:5f:f3:77:99:67:d6:66
          cleanup-tags: true
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          release: minor
          orb-name: circleci/orb-tools
          ssh-fingerprints: 66:04:99:1b:8e:51:e9:16:64:5f:f3:77:99:67:d6:66
          cleanup-tags: true
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          release: major
          orb-name: circleci/orb-tools
          ssh-fingerprints: 66:04:99:1b:8e:51:e9:16:64:5f:f3:77:99:67:d6:66
          cleanup-tags: true
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
