description: >
  This is the default executor using Docker and Alpine linux.

docker:
  - image: 'alpine:<<parameters.tag>>'
parameters:
  tag:
    default: latest
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/_/alpine?tab=tags
    type: string
